import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/providers";
import { cn } from "@heroui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased")}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
